---
- name: configuring the apache
  hosts: all
  tasks:
    - name: installing the apache
      apt:
        name: apache2
        state: present
        update_cache: yes
    - name: editing the index.html file
      copy:
        content: "Welcome to Apache chinta kiran"
        dest: /var/www/html/index.html
      notify: restart apache2
  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted
...
