---
- name: Installing the required S/W
  hosts: jenkinsserver
  tasks:
    - name: installing git , maven , java
      apt:
        name: "{{item.a}}"
        state: present
        update_cache: "{{item.b}}"
      with_items:
        - {a: git,b: yes}
        - {a: openjdk-11-jdk,b: no}
        - {a: maven,b: yes}
    - name: installing the jenkins war file
      get_url:
        url:  https://get.jenkins.io/war-stable/2.401.3/jenkins.war
        dest: /tmp
- name: installing tomcat on QA and Prod servers
  hosts: servers
  tasks:
    - name: installing tomcat
      apt:
        name: "{{item.a}}"
        state: present
        update_cache: "{{item.b}}"
      with_items:
        - {a: tomcat9,b: yes}
        - {a: tomcat9-admin,b: no}
    - name: copying the tomcat-users.xml file
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat9
    - name: restart the tomcat
      service:
        name: tomcat9
        state: restarted
...
