---
- name: creating a user and file/ directory
  hosts: all
  tasks:
    - name: creating a user
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
    - name: files and directory
      file: 
        name: "{{d}}"
        state: "{{e}}"
...
