---
- name: capture all OS info
  hosts: all
  tasks:
    - name: OS info
      debug:
        msg: "{{ansible_distribution}}"
    - name: OS version
      debug:
        msg: "{{ansible_distribution_version}}"
    - name: copy OS major version
      debug:
        msg: "{{ansible_distribution_major_version}}"
