---
- name: configuring the apache2/httpd
  hosts: all
  tasks:
    - name: installing the apache2 on Ubuntu
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: installing the httpd on RedHat
      yum:
        name: httpd
        state: present
        update_cache: yes
      when: ansible_distribution == "RedHat"
    - name: editing the index.html file
      copy:
        content: "Welcome kiran to Apache2"
        dest: /var/www/html/index.html
    - name: restarting the apache2 on Ubuntu
      service:
        name: apache2
        state: restarted
      when: ansible_distribution == "Ubuntu"
    - name: restarting the httpd on RedHat
      service:
        name: httpd
        state: restarted
      when: ansible_distribution == "RedHat"
    - name: checking the response from the servers
      uri:
        url: "{{item}}" 
        status_code: 200
      with_items:
         - http://172.31.1.24
         - http://172.31.11.238
         - http://172.31.15.32
