---
- name: configuring the tomcat
  hosts: all
  tasks:
    - name: installing the tomcat9 and tomcat9-admin
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
         - {a: tomcat9,b: present,c: yes}
         - {a: tomcat9-admin,b: present,c: no}
    - name: copying the tomcat-users file
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat9

    - name: replacing the port numbers
      replace:
        regexp: 8080
        replace: 9090
        path: /etc/tomcat9/server.xml
    - name: restart the tomcat9
      service:
        name: tomcat9
        state: restarted
    - name: pause the tomcat for 1 min
      pause:
        minutes: 1

    - name: check the response from the url
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.1.24:9090
        - http://172.31.11.238:9090
...
          
          
        
