---
- name: configuring the  apachae2
  hosts: all
  tasks:
    - name: installing the apache2 on Ubuntu
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: installing the apache2 on RedHat
      yum:
        name: httpd
        state: present
        update_cache: yes
      when: ansible_distribution == "RedHat"
    - name: edit the index.html file
      copy:
        content: "Welcome to apache2 Mr.kiran"
        dest: /var/www/html/index.html
    - name: restart the apache2 server
      service:
        name: apache2
        state: restarted
      when: ansible_distribution == "Ubuntu"
    - name: restart the httpd on redhat
      service:
        name: httpd
        state: restarted
      when: ansible_distribution == "RedHat"
    - name: checking the response from the servers
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
            - http://172.31.1.24
            - http://172.31.11.238
            - http://172.31.10.243    
