---
- name: installing/uninstalling
  hosts: all
  vars:
  - a: tomcat9
  - b: present
  - c: yes
  tasks:
    - name: install/unisntall
      apt:
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"
...

