---
- name: configuring the apache2
  hosts: all
  tasks:
   - name: installing the apache2
     apt:
       name: apache2
       state: present
       update_cache: no
   - name: editing the index.html file
     copy:
       content: "Testing the handler in apache2"
       dest: /var/www/html/index.html
     notify: restart apache
  handlers:
   - name: restart apache
     service:
       name: apache2
       state: restarted
...



