---
- name: Installing the application
  hosts: all
  tasks:
    - name: installing the Git on ubuntu
      apt:
        name: git
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: installing the git on Redhat
      yum:
        name: git
        state: present
        update_cache: yes
      when: ansible_distribution == "RedHat"  
